### ISSUE TITLE
upgrade.img not found

### ISSUE THREAD

**Issue by mhakala** [CSCfi/ansible-role-pxe_bootstrap#9]
In the tasks/redhat.yml there is a line fetching "upgrade.img" file. Seems that currently this image file is not present on mirror site. Also, I did not find out where this image is used in the first place. In case this is not required, can those line be removed from the role. I did not write PR as I'd like to double check I got this right.

**Comment by martbhell** [comment]
Perhaps @A1ve5 remembers? 

It was added here: https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_bootstrap/commit/e51213b159bf568dab194bff278dbe21a26dd063#diff-04cf94160c612df493cc6a3b98abb528

I suspect it's not used and it was added because it was also in that pxeboot directory in the mirror.

It is not fetched during a reinstall - (it's not seen in the Apache Httpd logs).

The upgrade.img is still there under the CentOS 7.2 location in the mirror.

@mhakala: Have you already updated to the CentOS 7.3 initrd and vmlinuz files? Is reinstall still working?

**Comment by martbhell** [comment]
Had a chat with tiggi - It could be used if one in the kickstart specify upgrade instead of install. Think one way would be to make this optional and disabled by default to fetch this file.

**Comment by martbhell** [comment]
Just tested - compute node reinstall does not work if repo points to CentOS7 (currently 7.3) while vmlinuz&initrd are from a 7.2. If one change the repo in the kickstart.cfg to point to 7.2.1511 then the reinstall works (and during post-actions it will yum update to 7.3).

**Comment by martbhell** [comment]
Moved this into review. Looks fine to me and CentOS 7.3 reinstall of a compute node works after one has run pxe_bootstrap role ( updated the initrd/vmlinuz files on the install node's www root)

**Comment by martbhell** [comment]
Not sure what to review.. this will get merged into fgci-ansible master in the next release.
